[WIP] - Follow-up osd-metrics-exporter integration
openshift/boilerplate pull request #124
Opened 2021-03-26 13:38 UTC by bdematte

Following the testing of the integration of the CSV generation in osd-metrics-exporter, integrating some of the gaps : 

- Python scripts generating the CSV shouldn't fail in case there is no crd to be included
- Several types of role (role or cluster-role) could be added to the cluster, so this needs to be supported
- Integrating the checks on the generated docker for 'replaced' version

Taking the opportunity to add migration guidelines (to be updated with next migrations)

2021-03-26 13:39 UTC, bdematte commented
Marking it as WIP for now as it is based on PR#119 updates

2021-04-08 12:54 UTC, jharrington22 requested changes

2021-04-08 12:57 UTC, bdematte commented on boilerplate/openshift/golang-osd-operator/csv-generate/README.md
> +3. The roles to be embedded in the CSV should be placed in `deploy/roles` repository
Not with the changes made within this PR (see updates in the python script)

2021-04-08 14:08 UTC, 2uasimojo commented on boilerplate/openshift/golang-osd-operator/csv-generate/README.md
> +For the migration, symlink may more convenient than `mv` or `cp` of the files (allowing to keep a single source but both `hack` and `common` generator working properly).
may be

2021-09-08 20:31 UTC, closed without merging