Update all images to RHEL9 and change app-sre image path
openshift/boilerplate pull request #420
Opened 2024-10-09 17:20 UTC by Mhodesty

The image path at registry.ci.openshift.org/ocp/builder is causing issues. Updating this to registry.ci.openshift.org/openshift/release to try to remedy this.

Also all instances of rhel-8 images being used have been updated to rhel-9.

2024-10-11 14:51 UTC, mjlshen requested changes

2024-10-11 14:51 UTC, mjlshen commented on config/Dockerfile
`ARG BASE_IMAGE` exists here because the base images used to be different between when this Dockerfile was used in Prow and when it was used in app-interface. Now that they are the same, we should remove this ARG + comment + corresponding pieces of `config/app-sre-build-push.sh` imo.

```
FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.22-openshift-4.17 AS builder
...
FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.22-openshift-4.17
```

2024-10-11 14:51 UTC, mjlshen commented on README.md
> +    FROM registry.ci.openshift.org/openshift/release:rhel-9-release-golang-1.22-openshift-4.17
```suggestion
    FROM registry.ci.openshift.org/openshift/release:rhel-8-release-golang-1.22-openshift-4.17
```

2024-10-11 14:51 UTC, mjlshen commented on config/Dockerfile.konflux
Similar to above, I would revert these changes as we don't want to change the base image at runtime

2024-10-11 15:01 UTC, Mhodesty commented on config/Dockerfile
Could you explain this a little bit further? I don't understand the application here in the sense that we're just updating the versioning.

2024-10-11 15:32 UTC, mjlshen commented on config/Dockerfile
Oh I mean that we are no longer overriding the base image in `config/app-sre-build-push.sh`

So we can just explicitly set the base image (without `ARG`), remove this comment
```
# When updating this default BASE_IMAGE, remember to also update it in app-sre-build-push.sh
```
and remove the override logic in `config/app-sre-build-push.sh`

2024-10-14 17:44 UTC, mjlshen approved these changes
/label tide/merge-method-squash
/lgtm

2024-10-14 18:05 UTC, merged